Fix test discovery
Using `TODO` on the top level breaks test discovery due to eager evaluation.
`./gradlew test` passes without running any tests.
As a workaround `TODO`s are wrapped in classes.

See sample stacktrace (from Intellij Idea) below:
```
> Task :test
Mar 24, 2020 9:56:45 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'kotlintest' failed to discover tests
kotlin.NotImplementedError: An operation is not implemented.
	at chapter6.exercises.Exercise_6_5Kt.<clinit>(Exercise_6_5.kt:9)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.kotlintest.runner.jvm.TestDiscovery.loadClasses(TestDiscovery.kt:118)
	at io.kotlintest.runner.jvm.TestDiscovery.discover(TestDiscovery.kt:44)
	at io.kotlintest.runner.junit5.KotlinTestEngine.discover(KotlinTestEngine.kt:69)
	...
```